linters:
  enable:
    - gocritic
    - gosec
    ## TODO: clean the list
    - gofmt
    - goimports
    - gocyclo
    - goconst
    # - prealloc
    - revive
    - stylecheck
    - unconvert
    # - unparam
    - errname
    - errchkjson

linters-settings:
  gocyclo:
    min-complexity: 17
