# TODO: remove this section once all linters support go 1.18
run:
  go: "1.17"

linters:
  enable:
    - gocritic
    - gosec
    ## TODO: clean the list
    - gofmt
    - goimports
    - gocyclo
    - goconst
    # - prealloc
    - revive
    - unconvert
    # - unparam

linters-settings:
  gocyclo:
    min-complexity: 16
